/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef test_TYPES_H
#define test_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace thrift_test {

class Record;


class Record : public virtual ::apache::thrift::TBase {
 public:

  Record(const Record&);
  Record& operator=(const Record&);
  Record() {
  }

  virtual ~Record() noexcept;
  std::vector<int64_t>  ids;
  std::vector<std::string>  strings;

  void __set_ids(const std::vector<int64_t> & val);

  void __set_strings(const std::vector<std::string> & val);

  bool operator == (const Record & rhs) const
  {
    if (!(ids == rhs.ids))
      return false;
    if (!(strings == rhs.strings))
      return false;
    return true;
  }
  bool operator != (const Record &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Record & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Record &a, Record &b);

std::ostream& operator<<(std::ostream& out, const Record& obj);

} // namespace

#endif
